# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSolarPowerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('power', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSolarPowerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_system_id', models.CharField(max_length=50, unique=True)),
                ('capacity', models.FloatField()),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='referencesolarpowerdata',
            name='solar_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.SolarSystem'),
        ),
        migrations.AddField(
            model_name='livesolarpowerdata',
            name='solar_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.SolarSystem'),
        ),
    ]
